# Generated by Django 5.1.6 on 2025-05-18 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
