# Generated by Django 5.2 on 2025-04-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commande_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.FloatField(default='500', max_length=200),
            preserve_default=False,
        ),
    ]
